FROM node:18-alpine AS base
WORKDIR /app

# Instala dependencias
COPY package*.json ./
RUN npm install --legacy-peer-deps

# Copia el resto del código y construye la app de Next.js
COPY . .
RUN npm run build

EXPOSE 3000
CMD ["npm", "start"]
